In [26]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [27]:
import distance

parser = distance.Parser()
d_matrix = parser.get_distance_matrix('cnnhealth.txt', distance.euclidean_distance)

Gathering vocabulary...


100%|██████████| 4061/4061 [00:00<00:00, 44859.75it/s]


Generating vectors...


100%|██████████| 4061/4061 [00:00<00:00, 47862.23it/s]


Generating text file...
Generating distance matrix...


100%|██████████| 4060/4060 [03:25<00:00, 19.75it/s] 


In [28]:
bow = parser.get_bag_of_words("cnnhealth.txt")

Gathering vocabulary...


100%|██████████| 4061/4061 [00:00<00:00, 57410.71it/s]


Generating vectors...


100%|██████████| 4061/4061 [00:00<00:00, 60684.14it/s]

Generating text file...


In [29]:
from single_link import SingleLink
import numpy as np

sl = SingleLink(num_clusters=8)
sl_clusters = sl.cluster(d_matrix)
unique, counts = np.unique(sl_clusters, return_counts=True)
print(unique)
print(counts)

Clustering with single link...
[0 1 2 3 4 5 6 7]
[4054    1    1    1    1    1    1    1]


In [33]:
from average_linkage import AverageLinkage

al = AverageLinkage(num_clusters=8)
al_clusters = al.cluster(d_matrix)
unique, counts = np.unique(al_clusters, return_counts=True)
print(unique)
print(counts)

Clustering with average linkage...
[0 1 2 3 4 5 6 7]
[4052    1    3    1    1    1    1    1]


In [36]:
from kmedoids import KMedoidsClustering

kmed = KMedoidsClustering(num_clusters=8)
kmed_clusters = kmed.cluster(d_matrix)
unique, counts = np.unique(kmed_clusters, return_counts=True)
print(unique)
print(counts)

Clustering with K-Medoids...
[0 1 2 3 4 5 6 7]
[2249  600    8  417   28  438  176  145]


In [32]:
from dbscan import DBScanClustering

for eps in range(10):
    db = DBScanClustering(eps=eps / 5 + 2)
    db_clusters = db.cluster(d_matrix)
    unique, counts = np.unique(db_clusters, return_counts=True)
    print(unique)
    print(counts)

Clustering with dbscan(eps=2.0)...
[-1  0  1]
[4047    7    7]
Clustering with dbscan(eps=2.2)...
[-1  0  1]
[4047    7    7]
Clustering with dbscan(eps=2.4)...
[-1  0  1  2  3  4  5  6]
[3972   48    7    5    5    6   11    7]
Clustering with dbscan(eps=2.6)...
[-1  0  1  2  3  4]
[3816  210   16    7    5    7]
Clustering with dbscan(eps=2.8)...
[-1  0  1  2  3]
[3493  549    7    5    7]
Clustering with dbscan(eps=3.0)...
[-1  0  1  2]
[2819 1228    7    7]
Clustering with dbscan(eps=3.2)...
[-1  0  1  2]
[2505 1536   13    7]
Clustering with dbscan(eps=3.4)...
[-1  0  1]
[2224 1830    7]
Clustering with dbscan(eps=3.6)...
[-1  0  1]
[1978 2076    7]
Clustering with dbscan(eps=3.8)...
[-1  0  1]
[1560 2494    7]


In [52]:
from spectral import SpecClustering
import math

sp = SpecClustering(num_clusters=8)
sp_clusters = sp.cluster(d_matrix)
unique, counts = np.unique(sp_clusters, return_counts=True)
print(unique)
print(counts)

Clustering with spectral clustering...
[0 1 2 3 4 5 6 7]
[ 422    1 1076  485  546  485  482  564]
